### ISSUE TITLE
Build error on yarn heliosup

### ISSUE THREAD

**Issue by biafra23** [cawfree/react-native-helios#15]
When executing `yarn heliosup` I get the following error:
```
   [...]
   Compiling once_cell v1.17.0
error: failed to run custom build command for `serde_derive v1.0.152`

Caused by:
  process didn't exit successfully: `/Users/biafra/react-native-helios/build/helios/target/release/build/serde_derive-b4d1d7d39eab0b63/build-script-build` (signal: 9, SIGKILL: kill)
warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `proc-macro2 v1.0.50`

Caused by:
  process didn't exit successfully: `/Users/biafra/react-native-helios/build/helios/target/release/build/proc-macro2-cf038779d97d9131/build-script-build` (signal: 9, SIGKILL: kill)
error: failed to run custom build command for `quote v1.0.23`

Caused by:
  process didn't exit successfully: `/Users/biafra/react-native-helios/build/helios/target/release/build/quote-ad757f818d10218c/build-script-build` (signal: 9, SIGKILL: kill)
error: failed to run custom build command for `serde v1.0.152`

Caused by:
  process didn't exit successfully: `/Users/biafra/react-native-helios/build/helios/target/release/build/serde-0214f8d9e3df33b2/build-script-build` (signal: 9, SIGKILL: kill)
error: failed to run custom build command for `syn v1.0.107`

Caused by:
  process didn't exit successfully: `/Users/biafra/react-native-helios/build/helios/target/release/build/syn-4cc9ab2b59b9e914/build-script-build` (signal: 9, SIGKILL: kill)
[2023-05-11T16:26:48Z INFO  cargo_ndk::cli] If the build failed due to a missing target, you can run this command:
[2023-05-11T16:26:48Z INFO  cargo_ndk::cli]
[2023-05-11T16:26:48Z INFO  cargo_ndk::cli]     rustup target install aarch64-linux-android
Error: Command failed: /Users/biafra/react-native-helios/build/helios/build.sh
    at checkExecSyncError (node:child_process:885:11)
    at Object.execSync (node:child_process:957:15)
    at AndroidHeliosFactory.compile (/Users/biafra/react-native-helios/scripts/heliosup.ts:195:19)
    at /Users/biafra/react-native-helios/scripts/heliosup.ts:675:54
    at Object.<anonymous> (/Users/biafra/react-native-helios/scripts/heliosup.ts:682:3)
    at Module._compile (node:internal/modules/cjs/loader:1267:14)
    at Module.m._compile (/Users/biafra/react-native-helios/node_modules/@commitlint/load/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1321:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/biafra/react-native-helios/node_modules/@commitlint/load/node_modules/ts-node/src/index.ts:1621:12) {
  status: 101,
  signal: null,
  output: [ null, null, null ],
  pid: 8490,
  stdout: null,
  stderr: null
}
✨  Done in 31.46s.
```

**Comment by biafra23** [comment]
I had the same issue when building helios from source with `--release`. When I removed `strip = true` from the section: `[profile.release]` the build succeeded.

**Comment by biafra23** [comment]
I forked your repo and changed the Cargo.toml in my fork and then changed repo and helios_checksum to my modified version. That fixes above error.

But now I have a new build error: ```
info: using existing install for 'stable-aarch64-apple-darwin'
info: default toolchain set to 'stable-aarch64-apple-darwin'

  stable-aarch64-apple-darwin unchanged - rustc 1.69.0 (84c898d65 2023-04-16)

Error: ENOENT: no such file or directory, copyfile '/Users/biafra/react-native-helios/build/helios/target/aarch64-linux-android/release/libhelios.so' -> '/Users/biafra/react-native-helios/android/src/main/jniLibs/arm64-v8a/libhelios.so'
    at Object.copyFileSync (node:fs:2951:3)
    at /Users/biafra/react-native-helios/scripts/heliosup.ts:647:12
    at Array.forEach (<anonymous>)
    at AndroidHeliosFactory.handleBuildCompletion (/Users/biafra/react-native-helios/scripts/heliosup.ts:637:62)
    at AndroidHeliosFactory.compile (/Users/biafra/react-native-helios/scripts/heliosup.ts:200:10)
    at /Users/biafra/react-native-helios/scripts/heliosup.ts:676:54
    at Object.<anonymous> (/Users/biafra/react-native-helios/scripts/heliosup.ts:683:3)
    at Module._compile (node:internal/modules/cjs/loader:1267:14)
    at Module.m._compile (/Users/biafra/react-native-helios/node_modules/@commitlint/load/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1321:10) {
  errno: -2,
  syscall: 'copyfile',
  code: 'ENOENT',
  path: '/Users/biafra/react-native-helios/build/helios/target/aarch64-linux-android/release/libhelios.so',
  dest: '/Users/biafra/react-native-helios/android/src/main/jniLibs/arm64-v8a/libhelios.so'
```

**Comment by biafra23** [comment]
https://github.com/a16z/helios/issues/240 tracks the initial issue.

**Comment by cawfree** [comment]
Hey @biafra23,

Sorry for the delay getting back to you.

Just for some context, how did this error come about? Did you make any changes to `heliosup`, like attempt to upgrade the Helios version? Or did this fail for you out-of-the-box?

Unfortunately one of the issues with our current implementation is our dependence upon nightly builds of the Rust toolchain, which may invalidate our setup.

It has been a while since I've sync'd `react-native-helios` with the latest distribution, so we can arrange to do this. In the mean time, the build published on [`npm`](https://npmjs.com/package/react-native-helios) should be working as expected.

Thanks for your patience with this issue.

**Comment by cawfree** [comment]
https://github.com/cawfree/react-native-helios/pull/16

**Comment by cawfree** [comment]
This issue has been resolved in [__0.1.22__](https://github.com/cawfree/react-native-helios/commit/580355364851ce8adb4932dd08e39c75af718a02) ([npm](https://www.npmjs.com/package/react-native-helios/v/0.1.22)).

Many thanks for your help!
